name: Build Test

on:
  workflow_dispatch
  
  
jobs:
    build-windows:
        strategy:
            matrix: 
                os: ["windows-latest"]
        runs-on: ${{ matrix.os }}
      
        steps:
          - name: Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.12' 
              
          - name: Clone Repo & Build
            run: |
              git clone https://github.com/xjunko/osr2png -b rewrite osr2png
              python -m pip install -r osr2png/requirements.txt
              cd osr2png
              python build.py
              
          - name: Finish building, zipping.
            run: |
              tree /F
              mkdir Release
              move osr2png/dist/osr2png.exe Release
              
          - name: Upload
            uses: actions/upload-artifact@v4
            with:
              name: win_x64
              path: Release

    build-unix:
        strategy:
            matrix: 
                os: ["ubuntu-latest"]
        runs-on: ${{ matrix.os }}
      
        steps:
          - name: Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.12' 
                
          - name: Install Dependecies
            run: |
              sudo apt-get install --quiet -y tree
              sudo apt-get install --quiet -y libfreetype6-dev libxau-dev libwebp-dev libpng16-16 liblzma-dev libjpeg-dev libbrotli-dev
              
          - name: Clone Repo & Build
            run: |
              git clone https://github.com/xjunko/osr2png -b rewrite osr2png
              python3.12 -m pip install -r osr2png/requirements.txt
              cd osr2png
              python3.12 build.py
              
          - name: Finish building, zipping.
            run: |
              tree
              mkdir Release
              mv osr2png/dist/osr2png Release
              
          - name: Upload
            uses: actions/upload-artifact@v4
            with:
              name: linux_x64
              path: Release
        
