name: Build Test

on:
  workflow_dispatch
  
  
jobs:
    build:
        strategy:
            matrix: 
                os: ["ubuntu-latest"]
        runs-on: ${{ matrix.os }}
      
        steps:
          - name: Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.10' 
                
          - name: Install Tools
            run: |
              sudo apt-get install --quiet -y tree
              
          - name: Clone Repo & Build
            run: |
              git clone https://github.com/xjunko/osr2png -b rewrite osr2png
              python3.10 -m pip install -r osr2png/requirements.txt
              cd osr2png
              python3.10 build.py
              
          - name: Finish building, zipping.
            run: |
              tree
              mkdir Release
              mv osr2png/dist/osr2png Release
              mv dist/osr2png Release
              
          - name: Upload
            uses: actions/upload-artifact@v2
            with:
              name: linux_x64
              path: Release
